import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Home | Webbriks',
    description: 'Generated by create next app',
};

export default async function Home() {
    return (
        <section className="padding-x padding-y">
            <div className="container">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Illum
                quis, ipsa quod cumque necessitatibus aperiam optio eum, dolorem
                quam natus provident soluta, ad culpa enim suscipit dolorum
                molestiae error. Possimus in facilis quia iusto nemo laboriosam
                rerum illo eligendi ex, officiis veniam sequi at consequuntur
                quaerat nesciunt modi obcaecati architecto placeat laudantium
                consequatur magni ad. Iste inventore rerum veniam corrupti totam
                officia illo ab pariatur odio quos, deserunt error minus fuga
                magnam exercitationem eligendi repellendus incidunt dolorum
                nostrum repudiandae qui fugit debitis! Cumque laboriosam
                recusandae ad veniam repellendus eius non praesentium, itaque
                cupiditate commodi sequi illum quidem sunt sint officiis aliquid
                tenetur eos suscipit modi incidunt! Praesentium itaque dolores
                ipsam natus quia asperiores adipisci reiciendis laborum. Maxime
                voluptatem ut delectus quod beatae asperiores, ipsam recusandae,
                consequatur magnam, aliquam eos quaerat enim alias deleniti?
                Soluta ea quis veritatis explicabo culpa hic amet doloribus
                eligendi impedit reprehenderit maxime cumque unde fuga, corrupti
                repellat eum temporibus odit eos cupiditate id voluptate
                tenetur. Qui, excepturi accusamus aliquam commodi nostrum
                pariatur ratione. Ullam, omnis repudiandae sequi labore
                excepturi atque doloribus quo deserunt nisi reiciendis dicta
                tempore modi in dolor laudantium culpa adipisci aut eveniet
                maxime quam sint nulla. Repellat veniam beatae magni nihil
                possimus perspiciatis dolorem voluptates at in, deserunt magnam
                mollitia recusandae consequuntur? Commodi sapiente nemo quaerat
                unde beatae doloremque officiis vero, rem dicta quidem
                recusandae expedita nihil, quo aperiam natus! Nisi at enim
                pariatur distinctio aliquam corrupti, consequuntur suscipit eos
                laboriosam ipsa fugit commodi sequi similique numquam nemo
                temporibus labore obcaecati soluta repellat aperiam. Assumenda,
                libero veniam ipsa nemo saepe voluptatibus vitae quam expedita
                iste! Consequatur amet nihil aliquam dolorum architecto quae
                voluptatibus exercitationem repellat nesciunt. Provident, vel
                unde ullam, accusamus doloremque accusantium laboriosam sed
                nesciunt modi et quisquam quidem ad eligendi aliquam molestias
                asperiores qui ipsum obcaecati perspiciatis inventore laborum
                nisi! Eligendi aliquid dolorem, nulla eveniet iste ex
                praesentium ut atque odit hic, quis iusto deserunt obcaecati
                maxime ipsum qui sit excepturi dignissimos illo deleniti, iure
                tempora facilis. Sapiente assumenda omnis animi doloribus magni
                vitae laboriosam aperiam nostrum? Perspiciatis nemo fugit
                provident ipsam tempora enim. Facere, eos maiores! Nemo minima
                eveniet ratione maxime beatae natus qui animi debitis commodi
                unde ducimus repudiandae quibusdam quasi error autem repellendus
                ex, atque minus voluptatum incidunt? Repudiandae, magni nam quia
                iure cupiditate perspiciatis itaque, quibusdam, repellat vero
                facilis voluptate debitis. Consequuntur iste libero possimus
                beatae omnis excepturi nulla iure quidem, exercitationem maiores
                fugiat error a voluptatem, quaerat expedita, aspernatur fuga
                nesciunt itaque delectus magnam ducimus debitis. Consequuntur
                voluptatibus aspernatur, cum ducimus cumque similique. Eligendi
                aliquid molestias, a qui nobis ullam est consectetur fugiat
                harum, dignissimos totam reiciendis aperiam consequuntur velit
                iusto corrupti libero ipsam autem exercitationem. Voluptas
                soluta, modi libero magnam distinctio similique totam itaque ad
                expedita atque, aliquid adipisci, molestias suscipit corrupti
                rem eius? Id nesciunt tempora, eum nobis, consectetur
                reprehenderit fugit, magnam in aut repellat tempore? Temporibus
                totam quasi animi recusandae eligendi? Odit minima vero nostrum
                sed iure, ratione sit animi ducimus atque error suscipit quo
                adipisci possimus rerum quidem dolores aspernatur fugit! Fugiat
                repellat quis alias veritatis eum culpa animi omnis tenetur?
                Nisi ea quo cumque dolores ad, eligendi non inventore quod at,
                quam sed doloremque vitae laboriosam saepe? Dolor adipisci natus
                aliquam cupiditate nesciunt. Itaque, debitis nihil! Aperiam
                beatae deserunt commodi cupiditate atque, veniam blanditiis nemo
                omnis deleniti nesciunt aspernatur dignissimos vitae voluptate
                quo reiciendis autem provident id praesentium enim minus
                tempora, repellendus adipisci! Unde, vel error ratione atque
                perspiciatis, culpa voluptates voluptatem totam, asperiores
                obcaecati adipisci. Nulla culpa laudantium nesciunt praesentium
                neque. Facilis amet corrupti animi id magni fugit perferendis
                nulla et unde voluptate nesciunt expedita culpa adipisci, fuga
                ullam voluptas hic esse ut accusantium laboriosam, est dolorem
                ab? Expedita dolorum voluptas eaque dignissimos cum harum,
                totam, tempore aperiam iusto nemo velit perferendis aliquam
                saepe optio ipsum, libero molestias quisquam repudiandae
                voluptatibus unde consequatur exercitationem aliquid. Repellat
                consequatur eius odit aliquam saepe nostrum illo, minima iure ex
                inventore eligendi pariatur et, laudantium cum molestias sed ea
                iste quibusdam tenetur! Quaerat consequatur quo eos iusto.
                Dignissimos ab dicta fugiat hic corporis molestias nihil rerum,
                ipsam quibusdam architecto alias vero illum obcaecati unde
                aliquid odit harum maxime ullam non! Eius vel neque deserunt
                facilis iste, eligendi esse, ad consequuntur perspiciatis
                doloremque commodi laudantium. Debitis, id ipsum voluptate
                asperiores soluta reiciendis non, voluptatem tempore, corrupti
                rem rerum! Nam et est totam sit dolore dolores a hic mollitia
                eaque voluptatum quaerat ex dignissimos, reiciendis commodi iure
                doloremque minus maiores cumque facere. Incidunt explicabo
                maiores veniam quas vel, illo placeat nostrum similique velit,
                dicta suscipit asperiores neque ratione, excepturi assumenda
                nobis dolor deleniti. Nam saepe dolore dolor aperiam numquam
                exercitationem nostrum porro? Unde, totam voluptate earum
                mollitia itaque enim aspernatur aliquam ipsam cupiditate autem
                delectus exercitationem at non! Libero ipsum natus eligendi
                consectetur dolores fuga, accusamus autem amet, ratione, dolore
                cumque. Repellat architecto pariatur eum optio dignissimos ipsa
                voluptates fugit facilis voluptatibus quod quas, numquam
                eligendi non earum a tempora quisquam tempore alias labore ab
                eaque dicta libero illum? Natus facere aperiam mollitia numquam
                fugit. Officia nulla aliquid eligendi iure id tempora laudantium
                neque dolorem, modi officiis et minima eos ut dolor delectus
                corporis laboriosam pariatur deserunt ullam quis ipsam placeat
                veritatis quo facere. Accusantium nobis, ex omnis odio quibusdam
                nulla alias amet eum a sit incidunt deserunt, maiores dolorem
                autem aspernatur labore ipsum repudiandae, laudantium earum
                cupiditate aut! Magni, autem rerum. Reiciendis sapiente
                inventore minus ut eaque est, possimus, officia expedita
                repudiandae libero, corporis iure cumque ratione nisi ea
                eligendi adipisci nam provident numquam aliquid tempore animi.
                Esse culpa consequuntur ipsa odit quasi, nobis consectetur
                mollitia doloremque maxime incidunt itaque molestiae dignissimos
                dolore saepe vitae accusantium tempore debitis cumque tempora
                minus ratione. Nulla ut, dolores porro voluptates facilis quo
                eaque maxime, odio odit, expedita labore laboriosam mollitia
                rem. Incidunt iusto sed magnam maiores. Voluptatibus ipsam hic
                sit quasi vel repellat natus? Voluptatum eveniet pariatur,
                praesentium dolorum est ea saepe eius rem omnis ipsum dolor in
                nihil harum quisquam. Reprehenderit numquam dolore officia
                asperiores mollitia, ex eligendi. Iusto rem aspernatur mollitia
                libero quia veritatis non pariatur!
            </div>
        </section>
    );
}
